// <auto-generated />
using System.CodeDom.Compiler;
using System.Data.Entity.Migrations;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

[GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
public sealed partial class tododecero : IMigrationMetadata
{
    private readonly ResourceManager Resources = new ResourceManager(typeof(tododecero));
    
    string IMigrationMetadata.Id
    {
        get { return "201901162114139_tododecero"; }
    }
    
    string IMigrationMetadata.Source
    {
        get { return null; }
    }
    
    string IMigrationMetadata.Target
    {
        get { return Resources.GetString("Target"); }
    }
}
